### ISSUE TITLE
Update readme file to reflect all data sources for CORDEX version

### ISSUE THREAD

**Issue by nhsavage** [MetOffice/PyPRECIS#123]
As part of moving the notebooks towards a focus on CORDEX-Core we need to ensure we acknowlege all data providers and remove the focus on the PRECIS model

**Comment by hsteptoe** [comment]
List of individual CORDEX citations, sourced from here: https://confluence.ecmwf.int/display/CKB/CORDEX%3A+Regional+climate+projections#CORDEX:Regionalclimateprojections-References

**AFR-CORDEX:**

- Nikulin G, Lennard C, Dosio A, et al. (2018) The effects of 1.5 and 2 degrees of global warming on Africa in the CORDEX ensemble, Environ. Res. Lett., doi:10.1088/1748-9326/aab2b4,  [http://iopscience.iop.org/article/10.1088/1748-9326/aab1b1](https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fiopscience.iop.org%2Farticle%2F10.1088%2F1748-9326%2Faab1b1&data=04%7C01%7CAndras.Horanyi%40ecmwf.int%7Cae835736980f48750f3008d8c6946d3b%7C21b711c6aab74d369ffbac0357bc20ba%7C0%7C0%7C637477688089293333%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dOp8u%2BUh8RG7EaWJz36XAhk%2BHlh%2BgqkpPU2JSwcJtIU%3D&reserved=0)
- Nikulin G., Jones, C. , Giorgi, F., et al. (2013)  Precipitation Climatology in An Ensemble of CORDEX-Africa Regional Climate Simulations,  J. Climate, 25, 6057–6078. http://doi.org/10.1175/JCLI-D-11-00375.1

**ANT-CORDEX:**

- Kittel, C., Amory, C., Agosta, C., et al. (2021): Diverging future surface mass balance between the Antarctic ice shelves and grounded ice sheet, The Cryosphere, 15, 1215–1236, https://doi.org/10.5194/tc-15-1215-2021.
- Lenaerts, J. T. M., van den Broeke, M. R., van de Berg, W. J., van Meijgaard, E., and Kuipers Munneke, P. (2012), A new, high-resolution surface mass balance map of Antarctica (1979–2010) based on regional atmospheric climate modeling, Geophys. Res. Lett., 39, L04501, https://www.doi.org/10.1029/2011GL050713
- Mottram, R., Hansen, N., Kittel, C., et al. (2020) What is the Surface Mass Balance of Antarctica? An Intercomparison of Regional Climate Model Estimates, The Cryosphere Discuss. [preprint], https://doi.org/10.5194/tc-2019-333

**ARC-CORDEX:**

- Inoue, J., Sato, K., Rinke, A., et al. (2021) Clouds and radiation processes in regional climate models evaluated using observations over the ice‐free Arctic Ocean, J. Geophys. Res. Atm., 126, e2020JD033904, http://doi.org/10.1029/2020JD033904
- Sedlar, J., M. Tjernström, A. Rinke, et al. (2020) Confronting Arctic troposphere, clouds and surface energy budget representations in regional climate models with observations, J. Geophys. Res. Atm., 124, http://doi.org/10.1029/2019JD031783
- Akperov, M., A. Rinke, I.I. Mokhov, et al. (2019) Future projections of cyclone activity in the Arctic for the 21st century from regional climate models (Arctic-CORDEX), Glob. Planet. Change, http://doi.org/10.1016/j.gloplacha.2019.103005
- Diaconescu, E.P., Mailhot, A., Brown, R. et al. (2018) Evaluation of CORDEX-Arctic daily precipitation and temperature-based climate indices over Canadian Arctic land areas, Clim. Dyn., 50, 2061–2085, doi:[doi.org/10.1007/s00382-017-3736-4](https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdoi.org%2F10.1007%2Fs00382-017-3736-4&data=04%7C01%7CAndras.Horanyi%40ecmwf.int%7Cae835736980f48750f3008d8c6946d3b%7C21b711c6aab74d369ffbac0357bc20ba%7C0%7C0%7C637477688089303328%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3%2Fz%2FBiThqCI8n6z5Bgk5r8qrF2o%2BtDmlDoY9CCCwZnU%3D&reserved=0)

**AUS-CORDEX:**

- Di Virgilio, G., Evans, J.P., Di Luca, A. et al. (2019) Evaluating reanalysis-driven CORDEX regional climate models over Australia: model performance and errors. Clim Dyn 53, 2985–3005. https://doi.org/10.1007/s00382-019-04672-w
- Evans, J.P., Di Virgilio, G., Hirsch, A.L. et al. (2020) The CORDEX-Australasia ensemble: evaluation and future projections. Clim Dyn. https://doi.org/10.1007/s00382-020-05459-0
- Di Virgilio, G., Evans, J.P., Di Luca, A. et al. (2020) Realised added value in dynamical downscaling of Australian climate change. Clim Dyn 54, 4675–4692. https://doi.org/10.1007/s00382-020-05250-1

**CAM-CORDEX:**

- Cavazos, T, Luna-Niño, R, Cerezo-Mota, R, et al. (2020) Climatic trends and regional climate models intercomparison over the CORDEX-CAM (Central America, Caribbean, and Mexico) domain. Int J Climatol.; 40: 1396– 1420. https://doi.org/10.1002/joc.6276
- Luna-Niño, R., Cavazos, T., Torres-Alavez, J.A. et al. (2020) Interannual variability of the boreal winter subtropical jet stream and teleconnections over the CORDEX-CAM domain during 1980–2010. Clim Dyn. https://doi.org/10.1007/s00382-020-05509-7

**CAS-CORDEX:**

- Top, S., Kotova, L., De Cruz, L., et al. (2021) Evaluation of regional climate models ALARO-0 and REMO2015 at 0.22° resolution over the CORDEX Central Asia domain, Geosci. Model Dev., 14, 1267–1293, https://doi.org/10.5194/gmd-14-1267-2021
- Ozturk, T., Turp, M. T., Türkeş, M., & Kurnaz, M. L. (2017). Projected changes in temperature and precipitation climatology of Central Asia CORDEX Region 8 by using RegCM4.3.5. Atmospheric Research, 183, 296–307. https://doi.org/10.1016/j.atmosres.2016.09.008

**EAS-CORDEX:**

- Sun, H., Wang, A. et al (2018) Impacts of global warming of 1.5°C and 2.0°C on precipitation patterns in China by regional climate model (COSMO-CLM). Atmos Res 203:83–94. https://doi.org/10.1016/j.atmosres.2017.10.024
- Teichmann, C., Jacob, D., Remedio, A.R. et al. (2020) Assessing mean climate change signals in the global CORDEX-CORE ensemble. Clim Dyn. https://doi.org/10.1007/s00382-020-05494-x

**EURO-CORDEX:**

- Kotlarski, S., Keuler, K., Christensen, O. B., et al. (2014) Regional climate modeling on European scales: a joint standard evaluation of the EURO-CORDEX RCM ensemble, Geosci. Model Dev., 7, 1297–1333, https://doi.org/10.5194/gmd-7-1297-2014
- Jacob, D., Teichmann, C., Sobolowski, S. et al. (2020) Regional climate downscaling over Europe: perspectives from the EURO-CORDEX community. Reg Environ Change 20, 51. https://doi.org/10.1007/s10113-020-01606-9
- Christensen, O.B., Kjellström, E. Partitioning uncertainty components of mean climate and climate change in a large ensemble of European regional climate model projections. Clim Dyn (2020). https://doi.org/10.1007/s00382-020-05229-y 
- Sørland SL, Schär C, Lüthi D, Kjellström E (2018) Bias patterns and climate change signals in GCM-RCM model chains. Environ Res Lett 13(7):074017. https://doi.org/10.1088/1748-9326/aacc77
- Coppola E., Nogherott o R. , Ciarlò J.M. et al . (2021) Assessment of the European climate projections as simulated by the large EURO-CORDEX regional and global climate model ensemble. Journal of Geophysical Research – Atmospheres,  [https:// doi.org/ 10.1029/2019JD032356](https://doi.org/10.1029/2019JD032356)
- V autard R., Kadygro v N. , Ile s C. et al.  (2021) Evaluation of the large EURO-CORDEX regional climate model ensemble . Journal of Geophysical Research – Atmospheres,  [https:// doi.org/10.1029/2019JD032344](https://doi.org/10.1029/2019JD032344)

**MED-CORDEX:**

- Ruti PM, Somot S, Giorgi F, et al. (201 6 ) MED-CORDEX initiative for Mediterranean Climate studies. Bull. Amer. Meteor. Soc. , 97(7), 1187-1208, July 2016, doi: [http://dx.doi.org/10.1175/BAMS-D-14-00176.1](https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdx.doi.org%2F10.1175%2FBAMS-D-14-00176.1&data=04%7C01%7CAndras.Horanyi%40ecmwf.int%7Cbd66e12a917340b51cd108d8ced39afd%7C21b711c6aab74d369ffbac0357bc20ba%7C0%7C0%7C637486755531585821%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uaxN%2B8aP0EDpc%2BKpJJM%2BtUsmYOmxpvxnDUgyn1HQDHc%3D&reserved=0),  [http://journals.ametsoc.org/doi/abs/10.1175/BAMS-D-14-00176.1](https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fjournals.ametsoc.org%2Fdoi%2Fabs%2F10.1175%2FBAMS-D-14-00176.1&data=04%7C01%7CAndras.Horanyi%40ecmwf.int%7Cbd66e12a917340b51cd108d8ced39afd%7C21b711c6aab74d369ffbac0357bc20ba%7C0%7C0%7C637486755531590810%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jA4Y55MaZahY855FuYCLXH9YEqpUjvrsbhHjtzvA7Y0%3D&reserved=0)
- Somot S., Ruti P., Ahrens B. et al. (2018 ). Editorial for the Med-CORDEX Special Issue. Clim. Dyn. 51(3):771-777, doi : 10.1007/s00382-018-4325-x, [https://link.springer.com/article/10.1007/s00382-018-4325-x](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Flink.springer.com%2Farticle%2F10.1007%2Fs00382-018-4325-x&data=04%7C01%7CAndras.Horanyi%40ecmwf.int%7Cbd66e12a917340b51cd108d8ced39afd%7C21b711c6aab74d369ffbac0357bc20ba%7C0%7C0%7C637486755531595801%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ve7Z2qAMncmMacRN%2FwsAdTY4dHauHskVzEVESQM4tO8%3D&reserved=0)
- Med-CORDEX  Special Issue, Climate Dynamics, volume 51, issue 3, 2018; https://link.springer.com/journal/382/volumes-and-issues/51-3

**MENA-CORDEX:**

- Zittis, G., Hadjinicolaou, P. and Lelieveld, J. (2014) Comparison of WRF Model Physics Parameterizations over the MENA-CORDEX Domain. American Journal of Climate Change, 3, 490-511. http://doi.org/10.4236/ajcc.2014.35042
- Almazroui, M. (2016) RegCM4 in climate simulation over CORDEX-MENA/Arab domain: selection of suitable domain, convection and land-surface schemes. Int. J. Climatol., 36: 236-251. https://doi.org/10.1002/joc.4340
- Bucchignani, E., Mercogliano, P., Rianna, G. and Panitz, H.-J. (2016) Analysis of ERA-Interim- driven COSMO-CLM simulations over Middle East – North Africa domain at different spatial resolutions. Int. J. Climatol., 36: 3346–3369. http://doi.org/10.1002/joc.4559 

**NAM-CORDEX:**

- Bukovsky, M. S., and Mearns, L. O. (2020). Regional climate change projections from NA-CORDEX and their relation to climate sensitivity. Clim. Change 162, 645–665.  https://link.springer.com/article/10.1007%2Fs10584-020-02835-x

**SAM-CORDEX:** 

- Blázquez, J., Silvina, A.S. Multiscale precipitation variability and extremes over South America: analysis of future changes from a set of CORDEX regional climate model simulations. Clim Dyn 55, 2089–2106 (2020). [https://doi.org/10.1007/s00382-020-05370-8](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1007%2Fs00382-020-05370-8&data=04%7C01%7CAndras.Horanyi%40ecmwf.int%7Cae835736980f48750f3008d8c6946d3b%7C21b711c6aab74d369ffbac0357bc20ba%7C0%7C0%7C637477688089313323%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UD5NsGw7jdPgUBuhW7lWFt2hm16x9LkIdC4wIy%2FGtVk%3D&reserved=0)
- Llopart, M., Simões Reboita, M. & Porfírio da Rocha, R. Assessment of multi-model climate projections of water resources over South America CORDEX domain. Clim Dyn 54, 99–116 (2020). [https://doi.org/10.1007/s00382-019-04990-z](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1007%2Fs00382-019-04990-z&data=04%7C01%7CAndras.Horanyi%40ecmwf.int%7Cae835736980f48750f3008d8c6946d3b%7C21b711c6aab74d369ffbac0357bc20ba%7C0%7C0%7C637477688089323315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pERnQK%2FAcA1YESYKjRCeYUaYcwBrehWSu8u9sYgCUKg%3D&reserved=0)
- Solman, S.A., Blázquez, J. Multiscale precipitation variability over South America: Analysis of the added value of CORDEX RCM simulations. Clim Dyn 53, 1547–1565 (2019). [https://doi.org/10.1007/s00382-019-04689-1](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1007%2Fs00382-019-04689-1&data=04%7C01%7CAndras.Horanyi%40ecmwf.int%7Cae835736980f48750f3008d8c6946d3b%7C21b711c6aab74d369ffbac0357bc20ba%7C0%7C0%7C637477688089323315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bHiFfEcdEDMIU1UIXVXtFu9dxpayPqtOa5aLZuonl9o%3D&reserved=0)
- Falco, M., Carril, A.F., Menéndez, C.G. et al. Assessment of CORDEX simulations over South America: added value on seasonal climatology and resolution considerations. Clim Dyn 52, 4771–4786 (2019). [https://doi.org/10.1007/s00382-018-4412-z](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1007%2Fs00382-018-4412-z&data=04%7C01%7CAndras.Horanyi%40ecmwf.int%7Cae835736980f48750f3008d8c6946d3b%7C21b711c6aab74d369ffbac0357bc20ba%7C0%7C0%7C637477688089333311%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Y%2FQJRAKIg3rsDOjcKILGxe7I8UD5z7%2BgySef8NgQdIg%3D&reserved=0)

**WAS-CORDEX:**

- Sanjay J, Krishnan R, Shrestha AB, Rajbhandari R, Ren G-Y (2017) Downscaled climate change projections for the Hindu Kush Himalayan region using CORDEX South Asia regional climate models. Adv Clim Chang Res 8(3):185–198,  https://doi.org/10.1016/j.accre.2017.08.003

**SEA-CORDEX:**

- Tangang, F., Chung, J.X., Juneng, L. et al. (2020) Projected future changes in rainfall in Southeast Asia based on CORDEX–SEA multi-model simulations. Clim Dyn 55, 1247–1267. https://doi.org/10.1007/s00382-020-05322-2
- CORDEX-CORE (comprehensive and homogeneous projections across almost all CORDEX domains with 0.22º resolution):
- Teichmann, C., Jacob, D., Remedio, A.R. et al. (2020) Assessing mean climate change signals in the global CORDEX-CORE ensemble. Clim Dyn.  [https://doi.org/10.1007/s00382-020-05494-x](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1007%2Fs00382-020-05494-x&data=04%7C01%7CAndras.Horanyi%40ecmwf.int%7Cae835736980f48750f3008d8c6946d3b%7C21b711c6aab74d369ffbac0357bc20ba%7C0%7C0%7C637477688089333311%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mz2aoiogwr6dk01k4pB3dqgumY%2FGJwq%2B%2BOrQSQelnSI%3D&reserved=0)
- Coppola, E., Raffaele, F., Giorgi, F. et al. (2021) Climate hazard indices projections based on CORDEX-CORE, CMIP5 and CMIP6 ensemble. Clim Dyn. https://doi.org/10.1007/s00382-021-05640-z

**Comment by hsteptoe** [comment]
I can't find any recommended acknowledgement text, but maybe a generic statement like:

> The PyPRECIS developers acknowledge the work of the [WCRP Coordinated Regional Climate Downscaling Experiment](https://cordex.org/) (CORDEX) and data from each of the CORDEX model partners who make their data open available via the globally distributed [Earth System Grid Federation](http://esgf.llnl.gov/) (ESGF) archives
