### ISSUE TITLE
Usage tracking

### ISSUE THREAD

**Issue by hsteptoe** [MetOffice/PyPRECIS#129]
We ought to consider some form of usage tracking for this repo.  The basic version we get under Insights > Traffic only gives us the last 2 weeks and isn't that informative.

More detailed usage statistics would give us a clearer picture of how many unique users we have and how this is changing over time.  This would help justify/rationalise future investments in time etc. Adding a DOI #122 will help with this to a certain extent, but tracking git interactions is still important.

**Comment by nhsavage** [comment]
@hsteptoe - do you have a link to any more info on how we could do this? Thanks.

**Comment by hsteptoe** [comment]
Turns out github don't make this very easy...

It looks like the most straightforward way might be to make sure that we always attached an 'asset' with our releases that way total downloads of the assets associated to a release are tracked, but https://github.community/t/counting-number-of-downloads-of-a-release/359 suggests we have to manually add an asset, not use the auto generated ones... I think

https://repo-analytics.github.io/ https://github.com/repo-analytics/repo-analytics.github.io  seems like it could be a solution, but possible requires giving away too many permissions.
