### ISSUE TITLE
Update notebooks to Iris 3.x

### ISSUE THREAD

**Issue by nhsavage** [MetOffice/PyPRECIS#135]
There were a significant number of breaking changes that came in at Iris v3.0 so there will be some minor rewriting neede to update the notebooks. It may make sense to delay this until an Iris realease includes [this PR](https://github.com/SciTools/iris/pull/4524) so that we can more easily load RegCM data over Africa (and perhaps other domains with Mercator)

This also implies creating a new conda environment and updating the lock file

**Comment by hsteptoe** [comment]
Once this happens I suggest we consider bumping up PyPRECIS to v3.0 to reflect these breaking changes

**Comment by nhsavage** [comment]
v3.3 includes the fix needed to correctly read RegCM data over Africa https://scitools-iris.readthedocs.io/en/v3.3.x/whatsnew/3.3.html

**Comment by nhsavage** [comment]
note that once this is completed, there is no longer any need for the attempt at chunking in  _5.2. Calculating percentiles_ (which doesn't actually work properly) because as of https://github.com/SciTools/iris/pull/3901 . There should be a follow on ticket created to do this.
