### ISSUE TITLE
Inconsistent location for location of data (historical in WS3 but not WS2)

### ISSUE THREAD

**Issue by nhsavage** [MetOffice/PyPRECIS#138]
The worksheets build on each other with data written in one worksheet being used in the next. If the location of data being written is not consistent this breaks the workflow.

Worksheet 2 has

# Save the new cube as a new netCDF file
OUTDIR = 'data_v2/EAS-22'

while worksheet 3 has:

# Directory name where processed data is stored 
HISTDIR = 'data_v2/EAS-22/historical'

this needs to be fixed

**Comment by rosannaamato** [comment]
Replaced OUTDIR with HISTDIR throughout worksheet 2. Fixed in 3f592f9.

**Comment by nhsavage** [comment]
closed by #143
