### ISSUE TITLE
update user documentation to support conda environment setup

### ISSUE THREAD

**Issue by rosannaamato** [MetOffice/PyPRECIS#142]
Issued identified as novice user: 

1) No Conda install instructions 

_Possible solution:_ 
> - follow this first to make sure conda is working properly: https://www-avd/sci/software_stack/conda_initial_how_to.html
> - If you think it's working properly, then try creating the pyprecis environment from https://github.com/MetOffice/PyPRECIS/blob/develop/environment.yml
> - https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file

2) when pyprecis-environment is activated in the terminal, it doesn't pull through to a jupter notebook opened from there. 

_Solution from Hamish:_ 
> So you need to have the following packages added to your conda env (they may already be there, check first 
>           `conda list --name <pyprecis env name>)`
>           `conda install ipykernel`
>           `conda install nb_conda_kernels`
>           the latter should pick up your conda envs automatically (but I haven't tested this), so if not working then do 
>           `ipython kernel install --user --name=<pyprecis env name>`
>           you'll need to restart you jupyter session to see them

**Comment by nhsavage** [comment]
this has also been an issue for INAMET (the technical person who set us the workshop was bot available)

**Comment by nhsavage** [comment]
also downloading data is not covered well. There are 3 possibilities:
1. the data you need is already on the system you want to use it from (e.g. the project disk at the Met Office). In this case the instructions need to be clear about the location to run the rsync from and the target
2. you download it from somewhere (e.g. precisrm) - in this case a recursive wget is needed and the instructions for this need to be included
3. we are using S3 (probably unlikely in the short term and should be removed as an option for now)
