### ISSUE TITLE
Update repo settings

### ISSUE THREAD

**Issue by hsteptoe** [MetOffice/PyPRECIS#43]
We need to agree and update repo settings, such as:

- [x] Agree default branch, this is currently `master` but we may want to make this `develop`
- [x] Agree branch protection policy, ie. agree who can commit to `master`
- [x] Agree branch creation policy (eg. can anyone create a branch?)
- [x] Make sure that all docs reflect these updates

**Comment by zmaalick** [comment]
We can see the practises in other groups. dev team option is good one.

**Comment by nhsavage** [comment]
@hsteptoe - would you want to be in the development team for this? That would mean it would be you me and Zubair. No one else has comitted to the repo that I can see.

**Comment by hsteptoe** [comment]
I am somewhat emotionally invested in the development of this project, but have no funded time to contribute much at the moment.

**Comment by nhsavage** [comment]
I have now updated master to main as well. All actions complete. People with a local repo will need to run the following commands:

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes
