### ISSUE TITLE
Move DATA-ACCESS.md into repo root

### ISSUE THREAD

**Issue by hsteptoe** [MetOffice/PyPRECIS#46]
I think given that we aren't using `git lfs` that there isn't currently a need to have a dedicated `data` dir, especially as it only contains the DATA-ACCESS.md information.

I propose moving DATA-ACCESS.md to the repo root and then removing this dir.

@balazagi @zmaalick any objections?

**Comment by balazagi** [comment]
> I think given that we aren't using `git lfs` that there isn't currently a need to have a dedicated `data` dir, especially as it only contains the DATA-ACCESS.md information.
> 
> I propose moving DATA-ACCESS.md to the repo root and then removing this dir.
> 
> @balazagi @zmaalick any objections?

give sense so fine by me!
