### ISSUE TITLE
Update Instruction

### ISSUE THREAD

**Issue by zmaalick** [MetOffice/PyPRECIS#77]
1. More clear description about compute access.Add print screen may be
2. About the brackets: use env vars

**Comment by balazagi** [comment]
Correct me if I am wrong but I thought we decided that the joining instructions are not to be included in the repo!

**Comment by zmaalick** [comment]
No, because that is for the workshops. But we decided the points I mentioned. Once it is complete, I will move this file to another repo.



________________________________

**Comment by nhsavage** [comment]
@zmaalick - can we close this or are there actions we need to take still?
