### ISSUE TITLE
Update Tutorial 3 

### ISSUE THREAD

**Issue by zmaalick** [MetOffice/PyPRECIS#81]
1. Projection example
2. 2. Consistant naming
3. Add more print out comments
4. Appropriate heading: "Calculating annual" and "mean annual cycle", and more explanations
5. Remove commented lines in last task
6. Add tibatan region lat lon in last task
7. Why we add bounds

**Comment by zmaalick** [comment]
@nhsavage  point 4 is due. 
point 7: description about bounds: we can add a subsection in tutorial 2.

**Comment by nhsavage** [comment]
made changes on annual cycle at 1888f0ff99513aab6fb1a7d08467dd5ff028d916
