### ISSUE TITLE
Create new version of training using CORDEX data in place of PRECIS

### ISSUE THREAD

**Issue by nhsavage** [MetOffice/PyPRECIS#98]
The PyPRECIS course delivering in Tajikstan was a very early version. Erasmo created some supplementary material while in country. including use of CORDEX data. As a step towards integrating anything from these notbooks that needs to go in the final verisons, I am creating branches to hold these - one per notebook for easier review

Tasks to complete this work:
- [x] New introduction using netCDF sample data and tutorial on merge issues (Notebook 1)
- [x] convert Notebook 2 to CORDEX
- [x] convert Notebook 3 to CORDEX
- [x] convert Notebook 4 to CORDEX
- [x] convert Notebook 5 to CORDEX
- [x] convert Notebook 6 to CORDEX
- [x] convert Worksheet 6 example code
- [x] convert Worksheet Solutions
- [x] make new CHIRPS data for 1986-2005 to match CORDEX
- [x] test and add RegCM data for section 3.4 (multimodel)
- [x] convert makedata notebook (section 4)
- [x] convert makedata notebook (section 5)
- [x] add CORDEX and other acknowlegments to readme file

**Comment by zmaalick** [comment]
Different trainings have different requirements. Should the first updated version be general enough to be easily modified to specific requirements ? or we pin point any one upcoming training like for example Angola one?

**Comment by nhsavage** [comment]
> Different trainings have different requirements. Should the first updated version be general enough to be easily modified to specific requirements ? or we pin point any one upcoming training like for example Angola one?

Very good question. I think that we should strive for something fairly generic. If we use the CORDEX core data, https://cordex.org/experiment-guidelines/cordex-core/cordex-core-simulations/ then we have 25km (0.22 degree) for all domains with only 2 RCMs to worry about. That should make adapting the basic parts for a given course more easy. For this ticket though I have a very simple set of objectives - just get these under version control, get the data needed and make it run under the pyprecis environment

**Comment by nhsavage** [comment]
ok, these all run on VDI now (they are much simpler than the ones on master)

**Comment by nhsavage** [comment]
Summary of status of these:

- these provide some useful example notebooks working with CORDEX not PRECIS data
- in their current format, they are not ready to be used for training as they don't include learning objectives, and most of the explanation is in comments not formatted cells

**Comment by nhsavage** [comment]
I've now started to rewrite the tutorials using CORDEX data on VDI. This will make use of some of Erasmo's work  - especially the parts on merge issues.

**Comment by nhsavage** [comment]
the rewritten first notebook is ready for review. This will require two types of review - code review and review by a member of the team who has completed the Award in Education and Training to look at the learning objectives in the new section and how well the notebook meets these.

To make review and merge simpler, I will use a different branch for each notebook

**Comment by nhsavage** [comment]
note that with the rewrite of section 1 done already, all of the material in Erasmo's notebooks is now covered in the training so I am deleting the branch with Erasmo's notbooks on

**Comment by nhsavage** [comment]
Tasks to complete this work:
- [ ] New introduction using netCDF sample data and tutorial on merge issues (Notebook 1)
- [ ] convert Notebook 2 to CORDEX
- [ ] convert Notebook 3 to CORDEX
- [ ] convert Notebook 4 to CORDEX
- [ ] convert Notebook 5 to CORDEX
- [ ] convert Notebook 6 to CORDEX
- [ ] convert Worksheet 6 example code
- [ ] convert Worksheet Solutions

**Comment by nhsavage** [comment]
second worksheet nearly complete but an issue has emerged 
1. the APHROIDTE data is for 1961-1990 but the available CORDEX data is 1971-2000
2. the data is not very CF compliant 

so an updated file will be needed

**Comment by nhsavage** [comment]
worksheet 3 includes info on dealing with rotated pole data. The problem here is that the CORDEX data is not strictly on a rotated pole 

```
	int rotated_latitude_longitude ;
		rotated_latitude_longitude:grid_mapping_name = "rotated_latitude_longitude" ;
		rotated_latitude_longitude:grid_north_pole_latitude = 90. ;
		rotated_latitude_longitude:grid_north_pole_longitude = 180. ;
		rotated_latitude_longitude:north_pole_grid_longitude = 0. ;
```

so we can 
skip this section (but need to explain how to handle it elsewhere with a different data set)
do rotation and explain not needed (or gloss over it)
use data for a different CORDEX domain for this section (implies a need for other obs)

**Comment by nhsavage** [comment]
for now, I will use the original data, note that it's not on a rotated pole (but that the coordinate system is)

**Comment by nhsavage** [comment]
The final section of worksheet 3 uses more GCMs downscaled with PRECIS> I instead propose to use the other RCM RegCM4. This probably also needs review from a person who has done the AET.

**Comment by nhsavage** [comment]
PRs #115 #116 #117 #118 #121 updated the notebooks and makedata notebook

**Comment by nhsavage** [comment]
final updates on #130 #132 and #133 - now all complete
